import React from 'react';
import {createRoot} from 'react-dom/client';
import {MemoryRouter} from 'react-router-dom';
import ActionDropdown from './src/component/common/ActionDropdown/ActionDropdown';
import SportsActionMenu from './src/component/pages/sportsdetails/SportsActionMenu';
import FinishedGameActionMenu from './src/component/pages/FinishedGame/FinishedGameActionMenu';
import './src/style.scss';
const names=['Deposit','Withdraw','InActive','Block Betting','Block Casino','Edit','Statement','Account Operations','Login Report','Downline','Reset Password'];
function App(){const [open,setOpen]=React.useState(false),[finished,setFinished]=React.useState(false),[result,setResult]=React.useState('');const items=names.map((label,key)=>({key:String(key),label:<div onClick={()=>setResult(label)}>{label}</div>}));return <MemoryRouter><div style={{padding:24,display:'flex',alignItems:'flex-start',gap:16,justifyContent:'flex-end',background:'#f5f6fb',minHeight:'100vh'}}><output style={{position:'absolute',left:12,top:90}}>{result}</output><ActionDropdown accountActions menu={{items}} trigger={['click']}><button style={{background:"#6147ff",border:0,borderRadius:10,color:"white",width:44,height:38,fontSize:24}} className="admin-details-more-action" aria-label="Account actions">⋮</button></ActionDropdown><SportsActionMenu match={{matchId:1,matchName:'Preview'}} isOpen={open} onToggle={setOpen} onCloseAll={()=>setOpen(false)} onSelectMatch={()=>{}} onPlusMinus={()=>setResult('Sports P&L')} onNavigate={setResult}/><FinishedGameActionMenu match={{matchId:1,eventName:'Preview'}} isOpen={finished} onToggle={setFinished} onCloseAll={()=>setFinished(false)} onSelectMatch={()=>{}} onPlusMinus={()=>setResult('Finished P&L')} onNavigate={setResult}/><ActionDropdown menu={{items:[{key:'0',label:<div><a href="#session">Session Bets</a></div>},{key:'1',label:<div><a href="#match">Match Bets</a></div>}]}} trigger={['click']}><button aria-label="Deleted actions">Deleted</button></ActionDropdown></div></MemoryRouter>};createRoot(document.getElementById('root')).render(<App/>);
